stages:
  - pre-build
  - build
  - test
  - deploy

pre-build:
  stage: pre-build
  script:
    - echo "Instalando dependencias del backend..."
    - pip install -r backend/requirements.txt
    - flake8 backend || true
    - pylint backend/app.py || true
    - echo "Instalando dependencias del frontend..."
    - cd frontend && npm install && npm audit || true

build:
  stage: build
  script:
    - echo "Compilando frontend..."
    - cd frontend && npm run build
    - echo "Preparando backend..."
    - mkdir -p dist
    - cp -r frontend/build/* dist/

test:
  stage: test
  script:
    - echo "Ejecutando pruebas del backend..."
    - pytest backend
    - echo "Ejecutando pruebas del frontend..."
    - cd frontend && npm test || true

deploy:
  stage: deploy
  script:
    - echo "Construyendo y desplegando la aplicación..."
    - docker build -t my-app:latest .
    - docker run -d -p 5000:5000 my-app
